### PR TITLE
Feat: obectsKeysAs feature

### PR DESCRIPTION
**Pull request by sielay**

### CODE REVIEW

**Review by Richard-Walton — APPROVED** [review]

**Review by drethegreat1 — APPROVED** [review]
lgtm

**Comment by jorinvo** [comment]
Hey there, happy to see people contributing!
I get the idea from the description in the code. I don't mind adding this. It seems like a more useful result than without the option.
For your particular use case have you considered setting mapAs to a different value?

**Comment by jorinvo** [comment]
Published the change as version 1.1.0 now: https://www.npmjs.com/package/edn-data

**Comment by sielay** [comment]
> Hey there, happy to see people contributing! I get the idea from the description in the code. I don't mind adding this. It seems like a more useful result than without the option. For your particular use case have you considered setting mapAs to a different value?

Hi. I played with mapAs but couldn't find the format that would work best for us in that case.

Kudos for the fast review and merge.

**Pull request merged**
